version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  server:
    build: ./webserver
    ports:
      - "3000:3000"
    volumes:
      - ./webserver:/app

  client:
    build: ./cli
    stdin_open: true
    tty: true
    volumes:
      - ./cli:/app
    working_dir: /app
    command: bash -c "g++ -std=c++11 -o main.exe main.cpp -lpthread && ./main.exe"
