version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - quiz-network

  server:
    build: ./webserver
    ports:
      - "3000:3000"
    depends_on:
      - mqtt
    volumes:
      - ./webserver:/app
    networks:
      - quiz-network
    environment:
      - MQTT_HOST=mqtt

  client:
    build: ./cli
    depends_on:
      - mqtt
    networks:
      - quiz-network
    stdin_open: true
    tty: true
    environment:
      - MQTT_HOST=mqtt

networks:
  quiz-network:
    driver: bridge